version: '3.9'

services:
  redwood:
    image: node:18.14.0
    volumes:
      - type: bind
        source: .
        target: /usr/local/app
      - unbound:/usr/local/app/node_modules
    working_dir: /usr/local/app
    command: bash -c "yarn install && yarn rw dev"
    restart: unless-stopped
    ports:
      - 8910:8910
      - 8911:8911
    networks:
      - redwood

volumes:
  unbound:

networks:
  redwood:
    name: redwood-network
