version: '3.9'

services:
  api:
    build:
      context: ../
      dockerfile: ./api/Dockerfile
      tags:
        - redwood-api:latest
    restart: unless-stopped
    expose:
      - 8911
    ports:
      - 8911:8911
    environment:
      - PORT=8911
      - DATABASE_URL=file:./dev.db
    networks:
      - redwood

networks:
  redwood:
    name: redwood-network
