version: '3.9'

services:
  web:
    image: node:18.14.0
    volumes:
      - ../:/usr/local/app
      - web-packages:/usr/local/app/node_modules
    command: bash -c "cd /usr/local/app && yarn install && yarn rw dev web"
    working_dir: /usr/local/app
    restart: unless-stopped
    expose:
      - 8910
    ports:
      - 8910:8910
    networks:
      - redwood

volumes:
  web-packages:

networks:
  redwood:
    name: redwood-network
